
template<int N>
int get_constant()
{
    return N;
}

int main(void)
{
    int sum;
    sum += get_constant<0>();
    sum += get_constant<1>();
    sum += get_constant<2>();
    sum += get_constant<3>();
    sum += get_constant<4>();
    sum += get_constant<5>();
    sum += get_constant<6>();
    sum += get_constant<7>();
    sum += get_constant<8>();
    sum += get_constant<9>();
    sum += get_constant<10>();
    sum += get_constant<11>();
    sum += get_constant<12>();
    sum += get_constant<13>();
    sum += get_constant<14>();
    sum += get_constant<15>();
    sum += get_constant<16>();
    sum += get_constant<17>();
    sum += get_constant<18>();
    sum += get_constant<19>();
    sum += get_constant<20>();
    sum += get_constant<21>();
    sum += get_constant<22>();
    sum += get_constant<23>();
    sum += get_constant<24>();
    sum += get_constant<25>();
    sum += get_constant<26>();
    sum += get_constant<27>();
    sum += get_constant<28>();
    sum += get_constant<29>();
    sum += get_constant<30>();
    sum += get_constant<31>();
    sum += get_constant<32>();
    sum += get_constant<33>();
    sum += get_constant<34>();
    sum += get_constant<35>();
    sum += get_constant<36>();
    sum += get_constant<37>();
    sum += get_constant<38>();
    sum += get_constant<39>();
    sum += get_constant<40>();
    sum += get_constant<41>();
    sum += get_constant<42>();
    sum += get_constant<43>();
    sum += get_constant<44>();
    sum += get_constant<45>();
    sum += get_constant<46>();
    sum += get_constant<47>();
    sum += get_constant<48>();
    sum += get_constant<49>();
    sum += get_constant<50>();
    sum += get_constant<51>();
    sum += get_constant<52>();
    sum += get_constant<53>();
    sum += get_constant<54>();
    sum += get_constant<55>();
    sum += get_constant<56>();
    sum += get_constant<57>();
    sum += get_constant<58>();
    sum += get_constant<59>();
    sum += get_constant<60>();
    sum += get_constant<61>();
    sum += get_constant<62>();
    sum += get_constant<63>();
    sum += get_constant<64>();
    sum += get_constant<65>();
    sum += get_constant<66>();
    sum += get_constant<67>();
    sum += get_constant<68>();
    sum += get_constant<69>();
    sum += get_constant<70>();
    sum += get_constant<71>();
    sum += get_constant<72>();
    sum += get_constant<73>();
    sum += get_constant<74>();
    sum += get_constant<75>();
    sum += get_constant<76>();
    sum += get_constant<77>();
    sum += get_constant<78>();
    sum += get_constant<79>();
    sum += get_constant<80>();
    sum += get_constant<81>();
    sum += get_constant<82>();
    sum += get_constant<83>();
    sum += get_constant<84>();
    sum += get_constant<85>();
    sum += get_constant<86>();
    sum += get_constant<87>();
    sum += get_constant<88>();
    sum += get_constant<89>();
    sum += get_constant<90>();
    sum += get_constant<91>();
    sum += get_constant<92>();
    sum += get_constant<93>();
    sum += get_constant<94>();
    sum += get_constant<95>();
    sum += get_constant<96>();
    sum += get_constant<97>();
    sum += get_constant<98>();
    sum += get_constant<99>();
    return sum;
}